import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
// import ReduxProvider from "@/providers/ReduxProvider";
import { Toaster } from "sonner";
import Providers from "@/lib/Providers/Providers";
// import { AntdRegistry } from "@ant-design/nextjs-registry";

const poppins = Poppins({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html>
        <body className={`${poppins.className}`}>
          <>
            <Toaster position="top-center" />
            {children}
            {/* <AntdRegistry></AntdRegistry> */}
          </>
        </body>
      </html>
    </Providers>
  );
}
